name: retake
channels:
  - defaults
dependencies:
  - python==3.11
  - pip:
      - numpy==1.26.4
      - scipy==1.14.1
      - torch==2.4.0
      - torch-npu==2.4.0
      - torchvision==0.19.0
      - transformers==4.45.2
      - accelerate==0.34.2
      - av==13.1.0
      - pyyaml==6.0.2
      - opencv-python-headless==4.10.0.84
      - pandas==2.2.3
      - pysubs2==1.7.3
      - pyarrow==17.0.0
      - openai==1.56.0
      - tqdm==4.67.1
      - attrs==23.2.0
      - decorator==5.2.1
